version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron" 
      value: "0 0 1 */2 *" 

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron" 
      value: "0 0 1 */2 *" 

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron" 
      value: "0 0 1 */2 *" 
