name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-2025, macos-15]
    
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Setup pnpm via corepack
      run: |
        corepack enable
        corepack prepare pnpm@latest --activate
        
    - name: Install dependencies
      run: pnpm install
        
    - name: Run build
      run: pnpm run build